operations = () => {
    var name  = document.getElementById("name").value;
    var ph = document.getElementById("number").value;
    var cnic = document.getElementById("cnic").value;
    var email = document.getElementById("email").value;
    var password = document.getElementById("password").value;
    var confirmPass = document.getElementById("confirmpassword").value;
    var age = document.getElementById("age").value;
    var male = document.getElementById("male").checked;
    var female = document.getElementById("female").checked;
    alert(name);
}




